<?
$dbase="siteConfig";
$title = 'SMS Ayarları';
$ozellikler = array(ekle=>'0', 
					baseid=>'ID',
					listDisabled => true,
					listBackMsg => 'Kaydedildi',
					editID=>1,
					);

$icerik = array(
				array(isim=>'SMS Gönderimi Aktif',
					  db=>'SMS_kullan',
					  stil=>'checkbox',
					  gerekli=>'0'),
				array(isim=>'Mobile Notification Aktif',
					  info=>'ShopPHP Mobile App. (IOS / Android) kullanan siteler içindir.',
					  db=>'mn_kullan',
					  stil=>'checkbox',
					  gerekli=>'0'),
				array(isim=>'Mobile Notification Firma Adı',
					  info=>'ShopPHP Mobile App. (IOS / Android) kullanan siteler içindir.',
					  db=>'mn_name',
					  stil=>'normaltext',
					  gerekli=>'0'),
				array(isim=>'Mobile Notification Google App Key',
					  info=>'ShopPHP Mobile App. (IOS / Android) kullanan siteler içindir.',
					  db=>'mn_key',
					  stil=>'normaltext',
					  gerekli=>'0'),
				array(isim=>'SMS No',
					  db=>'SMS_no',
					  stil=>'normaltext',
					  unlist=>true,
					  gerekli=>'0'),
				array(isim=>'SMS Firma',
					  db=>'SMS_Firma',
					  stil=>'simplepulldown',
					  align=>'left',
					  width=>40,
					  simpleValues=>'9|Turkiye SMS,1|Figensoft,2|Alo/Mutlu SMS,3|Net GSM,22|Net GSM OTP,4|Ucuz SMS Al,5|Avea Kurumsal,6|Ucuz SMS Gönder,7|Barabut,8|Setafon (SMS Kutusu),10|SMS Origin,11|Toplu SMS API (İleti Merkezi),13|Kurecell SMS,15|Tescom,16|Verimor,17|Nida Telekom,18|DataPort,19|Nac.com.tr,20|Mas GSM,21|1 SMS,23|Uslucan Telekom',
					  gerekli=>'1'),
				array(isim=>'SMS Originator',
					  info=>'SMS gönderiminde, gönderen kısmında gözükecek başlık. Yasal olarak buranın, SMS entegratör firmada yazan ile aynı olması gerekir. ',
					  db=>'SMS_originator',
					  stil=>'normaltext',
					  unlist=>true,
					  gerekli=>'0'), 						  							  
				array(isim=>'SMS Kullanıcı Adı',
					  db=>'SMS_username',
					  stil=>'normaltext',
					  unlist=>true,
					  gerekli=>'0'), 					  
				array(isim=>'SMS Şifre',
					  db=>'SMS_password',
					  stil=>'normaltext',
					  unlist=>true,
					  gerekli=>'0'), 	
				array(isim=>'SMS Footer Info',
					  db=>'SMS_footer',
					  stil=>'normaltext',
					  info=>'Buraya girdiğiniz yazı, her gönderilen SMS mesajının sonuna eklenir.',
					  unlist=>true,
					  gerekli=>'0'),	  
			
			 	);
				admin($dbase,$where,$icerik,$ozellikler);
?>