<?
$dbase="temp_workshop";
$tempInfo.=adminInfo('Bu ayarlar, v4.6 sürümünden itibaren şablon geliştirenlere örnek olması için <strong>/templates/workshop/ayalar.php</strong> dosyasına eklenmiştir. Bu girişlerin <strong>Workshop şablonu</strong> üzerinde bir etkisi yoktur.');

$icerik = array(
				array(isim=>'Test Başlık',
					  db=>'test',
					  multilang=>true,
					  stil=>'normaltext',
					  gerekli=>'0'),
				array(isim=>'Kişisel Logo',
					  db=>'logo',
					  width=>50,
					  stil=>'file',
					  uploadto=>'images/',
					  gerekli=>'0'), 
				array(isim=>'Kısa Detay Yazısı',
					  db=>'onDetay',
					  maxlength=>512,
					  unlist=>true,
					  stil=>'textarea',
					  multilang=>true,
					  rows=>'4',
					  cols=>'64'),
				array(isim=>'Uzun Detay Yazısı',
					  db=>'detay',
					  stil=>'HTML',
					  multilang=>true,
					  en=>'450',
					  boy=>'150',
					  unlist=>true,
					  gerekli=>'0'),	
				array(isim=>'Kategori Seçimi',
					  db=>'kategoriler',
					  stil=>'multiplechoice',
					  unlist=>true,
					  multiplechoice_data =>array(db=>'urun',
					  						  base=>'ID',
											  name=>'name',
											  where=>'bakiyeOdeme = 0 AND active=1'
											  ),
					  gerekli=>'0'),		
				array(isim=>'Ürün Seçimi',
					  db=>'urunler',					  
					  stil=>'multiplechoice',
					  unlist=>true,
					  multiplechoice_data =>array(db=>'urun',
					  						  base=>'ID',
											  name=>'name',
											  where=>'bakiyeOdeme = 0 AND active=1'
											  ),
					  gerekli=>'0'),
				array(isim=>'Kelime Seçimi',
					  db=>'secim',
					  unlist=>true,
					  stil=>'simplepulldown',
					  align=>'left',
					//  multilang=>true,
					  width=>50,
					  simpleValues=>'Deneme,Diğer Deneme,Farklı Deneme'),	
				array(isim=>'Deneme Aktif',
					  db=>'active',
					  stil=>'checkbox',
					  width=>29,
					  gerekli=>'0'),	
				  );
				
?>